require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EquipesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Equipe. As you add validations to Equipe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EquipesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all equipes as @equipes" do
      equipe = Equipe.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:equipes)).to eq([equipe])
    end
  end

  describe "GET show" do
    it "assigns the requested equipe as @equipe" do
      equipe = Equipe.create! valid_attributes
      get :show, {:id => equipe.to_param}, valid_session
      expect(assigns(:equipe)).to eq(equipe)
    end
  end

  describe "GET new" do
    it "assigns a new equipe as @equipe" do
      get :new, {}, valid_session
      expect(assigns(:equipe)).to be_a_new(Equipe)
    end
  end

  describe "GET edit" do
    it "assigns the requested equipe as @equipe" do
      equipe = Equipe.create! valid_attributes
      get :edit, {:id => equipe.to_param}, valid_session
      expect(assigns(:equipe)).to eq(equipe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Equipe" do
        expect {
          post :create, {:equipe => valid_attributes}, valid_session
        }.to change(Equipe, :count).by(1)
      end

      it "assigns a newly created equipe as @equipe" do
        post :create, {:equipe => valid_attributes}, valid_session
        expect(assigns(:equipe)).to be_a(Equipe)
        expect(assigns(:equipe)).to be_persisted
      end

      it "redirects to the created equipe" do
        post :create, {:equipe => valid_attributes}, valid_session
        expect(response).to redirect_to(Equipe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved equipe as @equipe" do
        post :create, {:equipe => invalid_attributes}, valid_session
        expect(assigns(:equipe)).to be_a_new(Equipe)
      end

      it "re-renders the 'new' template" do
        post :create, {:equipe => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested equipe" do
        equipe = Equipe.create! valid_attributes
        put :update, {:id => equipe.to_param, :equipe => new_attributes}, valid_session
        equipe.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested equipe as @equipe" do
        equipe = Equipe.create! valid_attributes
        put :update, {:id => equipe.to_param, :equipe => valid_attributes}, valid_session
        expect(assigns(:equipe)).to eq(equipe)
      end

      it "redirects to the equipe" do
        equipe = Equipe.create! valid_attributes
        put :update, {:id => equipe.to_param, :equipe => valid_attributes}, valid_session
        expect(response).to redirect_to(equipe)
      end
    end

    describe "with invalid params" do
      it "assigns the equipe as @equipe" do
        equipe = Equipe.create! valid_attributes
        put :update, {:id => equipe.to_param, :equipe => invalid_attributes}, valid_session
        expect(assigns(:equipe)).to eq(equipe)
      end

      it "re-renders the 'edit' template" do
        equipe = Equipe.create! valid_attributes
        put :update, {:id => equipe.to_param, :equipe => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested equipe" do
      equipe = Equipe.create! valid_attributes
      expect {
        delete :destroy, {:id => equipe.to_param}, valid_session
      }.to change(Equipe, :count).by(-1)
    end

    it "redirects to the equipes list" do
      equipe = Equipe.create! valid_attributes
      delete :destroy, {:id => equipe.to_param}, valid_session
      expect(response).to redirect_to(equipes_url)
    end
  end

end
